### ISSUE TITLE
[REQUEST]  Auto accept current item after a timeout

### ISSUE THREAD

**Issue by QiangF** [davatorium/rofi#1066]
This is to minimize typing. Take the window cycle for example, often binds to Alt-Tab. There is just two cases.

1.  the target window is on the default row, (or you know it's position and use xdotool to get there automatically). The best solution is hit Alt-Tab and get to the target window.
2. the target window is down on the list, then further seeking is required, and the user will normally start typing withing 1 second.

So I think we can add a configurable option --auto-accept-delay, if rofi is fired up and no user input after that delay,  do action on the current item.

Version: 1.5.1

**Comment by DaveDavenport** [comment]
Maybe an close-after timeout might be nice too. 

Will consider it.

**Comment by sl5net** [comment]
May set first window the last if those feature is chosen

**Comment by sl5net** [comment]
Maybe you could help with this workaround: https://stackoverflow.com/questions/64511101/autokey-remember-last-window-name-in-global-variable

**Comment by smekkley** [comment]
Some workaround is mentioned in #38 . 
In my case, `xdotool sleep 0.2 key Tab` before running the rofi helps emulating the normal ctrl+tab/alt+tab behaviour with rofi. But it's bit flaky. If I release control too early, rofi stays open, instead of switching to the next window. Also UI is bit awkward, as you can see the cursor moves down as soon as rofi gets opened.  
It'd be nice to have an official support, but maybe it's outside the scope of this project.

**Comment by DaveDavenport** [comment]
Configuration looks like:

```css
configuration {
  timeout {
      delay:  15;
      action: "kb-cancel";
  }
}
```

Both delay and action need to be set.
Action can be any of the keybindings as shown in `rofi -show keys`.

(-timeout-delay 15 -timeout-action "kb-cancel"  on commandline.).

**Comment by DaveDavenport** [comment]
please test and see if this does what is requested.
