### ISSUE TITLE
[REQUEST] Select multiple windows to close in window mode

### ISSUE THREAD

**Issue by eadventurous** [davatorium/rofi#1071]
**Describe the feature**
It would be nice to be able to select not one, but multiple windows in `window` mode and then close them all. Not to restart rofi in wondow mode multiple times.

**Expected behavior**
For example like in `dmenu` press `Shift+Enter` to select window, when `n` windows are selected press `Shift+del` to close them all.

- Rofi version: `Version: 1.5.1`

Sorry if this is a duplicate, but I have not found another issue like this, multiple select is only available in `dmenu` mode as I understand.

**Comment by wheatdog** [comment]
I would also like to see this feature!

**Comment by gnarendran** [comment]
Just familiarizing with i3wm and rofi, and found this feature would be nice to have. For i3 had to emulate the feature using the pipeline i3-msg -> jq->column->rofi -multi-select -dmenu->sed->xargs i3-msg kill.

**Comment by DaveDavenport** [comment]
Can you link that script?

**Comment by gnarendran** [comment]
@DaveDavenport: script i3-killWindows.sh attached. But please do note that this my first stab at jq so it may not be very concise etc.!
[i3-killWindows.sh](https://github.com/davatorium/rofi/files/6719500/i3-killWindows.sh.txt)

**Comment by DaveDavenport** [comment]
thx

**Comment by tuurep** [comment]
Hello I'm looking for a solution to this issue: closing windows in bulk while in `rofi -show window`

What you're suggesting (marking windows and closing all marked) is nice.

I would also be satisfied with the following:

When pressing <kbd>Shift</kbd> + <kbd>Del</kbd> to close a window, it wouldn't close the window list.

Could it be for example scriptable so that when in window mode I press <kbd>Shift</kbd> + <kbd>Del</kbd> it will run `rofi -show window` immediately after, and it's not visible that it closes in between?

Also is it possible to remap <kbd>Shift</kbd> + <kbd>Del</kbd> to something else, for example if I would prefer <kbd>Ctrl</kbd> + <kbd>Q</kbd>? Or create custom maps?

**Comment by DaveDavenport** [comment]
@tuurep  please follow the guidelines, don't ask questions that are not directly related to the issue (e.g. remapping keys).

**Comment by eadventurous** [comment]
@DaveDavenport I think there is a typo in the commit that closes it, I added a comment there.
