### ISSUE TITLE
[REQUEST] Add "show" to config.rasi

### ISSUE THREAD

**Issue by dnut** [davatorium/rofi#1121]
#### Background
Many of the command line arguments simply override `config.rasi` settings. Having a central configuration is great because you don't have to type a complicated command every time you start the app. You don't have to go everywhere in your system that invokes rofi to modify the command line. You can control the configuration using a purpose-built file format stored in a standardized location.

#### Problem
Unfortunately, the most important configuration, `-show`, does not conform to this pattern, so the app is unusable without including this argument every time. 

#### Solution

Add an option called "show" to config.rasi that will be used unless overridden by the command line.
```css
configuration {
    show: "combi";
}
```
With the above configuration, this command should open combi mode as if `-show combi` were used:
```bash
rofi
```
This command would behave as it normally would, overriding the config.rasi setting.
```bash
rofi -show drun
```

**Comment by DaveDavenport** [comment]
It nicely conforms to the pattern. There is a separation between options that can and cannot be changed from the config.  (-e, -dmenu, -show,-h,-dump-config,-upgrade-config,etc.)

These options tell rofi what action to perform when launching, other options modify look/behavior (these can be changed in config).

Setting 'what action to perform' in config file will possibly break applications that call rofi.

Not going to change this behavior,  running 'rofi -show' is not a complicated command. 

> You don't have to go everywhere in your system that invokes rofi to modify the command line.

I don't see how this even applies, you suddenly going to call rofi with a completely different action? (dmenu mode instead of showing the default mode?).
