### ISSUE TITLE
[REQUEST] Text/word wrap

### ISSUE THREAD

**Issue by katacarbix** [davatorium/rofi#1130]
**Describe the feature**

Add the option to wrap long lines of text in entries. There should be a property for `listview` in themes with possible values of `none`, `soft`, and `hard`. `soft` splits at spaces, and `hard` splits words.

**Rofi version**

1.5.4

**Comment by ckp95** [comment]
+1 to this, it is very annoying on small screens when trying to select long files / paths. For example these simple filenames are longer than what Rofi can display:

![image](https://user-images.githubusercontent.com/43073868/115960098-48d1df80-a507-11eb-9f4d-2e0ef55b7c93.png)

It is even worse when I am using dmenu mode to choose from full paths where something is buried many folders deep, to the extent that I can't actually tell what the selection is because the filename is obscured:

```
/long/list/of/directory/names/...
                                ^ filename is entirely cut off

It would be great if rofi could wrap the lines it shows when displaying them. It wouldn't need to wrap when writing to stdout, just for display.
```

**Comment by DaveDavenport** [comment]
There is ellipsizing keybinding you can have it ellipsize in the middle. (see manpage).

Wrapping comes with it own issues, mostly related to variable height element (that is not going to be implemented, for this see several of the other issues asking for this). 

As it stands , I currently do not have time to implement this. 

On side note I don't get the issue fully: file browser does not show full path in entry, only file name.  So unsure how filename is entirely cut off?

**Comment by ckp95** [comment]
>On side note I don't get the issue fully: file browser does not show full path in entry, only file name (see your own screenshot). So unsure how filename is entirely cut off?

Not in that particular screenshot, but I often pipe lists of file paths into rofi with the `-dmenu` option. In that case the filenames do get cut off quite often.

I did not know about the ellipsizing keybindings; I've just tried it and it solves the problem for me.
