### ISSUE TITLE
[BUG] can't launch .desktop with additional argument

### ISSUE THREAD

**Issue by coiby** [davatorium/rofi#1143]
## Version

Version: 1.5.4

## Configuration

https://gist.github.com/coiby/87259ab17a0f8a2257719b638465943c

## Launch Command

rofi -show drun

## Steps to reproduce

1. Customize a .desktop, for example, add `-R` option for `/usr/share/applications/vim.desktop`
```bash
Exec=vim -R %F
```
2. Search for vim in rofi

## What behaviour you see

The application won't be launched and the following error is shown
```
xfce4-terminal: Unknown option "-R"
```

## What behaviour you expect to see

The modified .desktop could be launched.

**Additional details:**
`gtk-launch vim` could successfully launch the modified desktop.

**Comment by sardemff7** [comment]
This is an issue with your terminal.
The default for rofi is to run `terminal -e command args…` (the setting is `run-shell-command`).
From its man page, xfce4-terminal uses `-e` for a single argument, you would need to use `-x` here.
I would set `terminal` to `xfce4-terminal` and `run-shell-command` to `{terminal} -x {cmd}` in your case. (As we should probably drop xfce4-terminal from our wrapper script, since it cannot work with the default configuration.)

**Comment by sardemff7** [comment]
xfce4-terminal replaced with the wrapper version in 2da2a1f4dc9513fde9355b10569bccb1a1742db3

**Comment by coiby** [comment]
Thank you for the quick reply and clearing up this issue!
