### ISSUE TITLE
[BUG] Rofi does not play nice with hidden .desktop files

### ISSUE THREAD

**Issue by AlexApps99** [davatorium/rofi#1333]
## Version

```
$ rofi -v
Version: 1.6.1
```

## Launch Command

`rofi -modi drun -show drun`

## Steps to reproduce

1. Have desktop file `/usr/share/applications/foo.desktop`
2. Right click hide it from the Xfce 4 Whisker menu
This generates the following file at `~/.local/share/applications/foo.desktop`
```ini
[Desktop Entry]
Hidden=true

```

## What behaviour you see

- It is not hidden

## What behaviour you expect to see

- It should be hidden

**Additional details:**
- I ran the command with `G_MESSAGES_DEBUG=Dialogs.DRun`
  - Generated errors in the format `[foo.desktop] [~/.local/share/applications/foo.desktop] Invalid desktop file: No type indicated`

This issue seems to be a duplicate of #453, only it was closed without being fixed.
You are correct that it is not valid to the spec, however having a fallback in the case that a required key is not present will never affect the parsing of valid desktop files, so there's no reason not to.
Especially since Xfce 4 (a very common DE) generates files in this manner

**Comment by DaveDavenport** [comment]
Not sure why bot did not close it, it should have.

For me it is very simple, if I start supporting one 'non-standard' desktop file, I should support them all.  This will be hard to maintain and most likely be buggy.
But more importantly I would like to understand why this issue is filed in the rofi issue tracker?  and not in the issue tracker of the application that generated the broken desktop file.
To me this would be the logic place to file this issue?

**Comment by AlexApps99** [comment]
Fair enough, I guess

**Comment by DaveDavenport** [comment]
Thanks for understanding!
I was just about to report an issue @ xfce and I saw you created one: https://gitlab.xfce.org/panel-plugins/xfce4-whiskermenu-plugin/-/issues/53

thanks!

**Comment by DaveDavenport** [comment]
fixed in whiskermenu!
