### ISSUE TITLE
[BUG] Issues with the new window setting close-on-delete: false

### ISSUE THREAD

**Issue by DaveDavenport** [davatorium/rofi#1406]
### Discussed in https://github.com/davatorium/rofi/discussions/1404

<div type='discussions-op-text'>

<sup>Originally posted by **tuurep** August 31, 2021</sup>
Hello, I've been trying out this new config option:

```
window {
    close-on-delete: false;
}
```

The idea is to open `rofi -show window` for the purpose of closing many windows on one go.

It works such that it doesn't exit on delete-entry (<kbd>Shift</kbd> + <kbd>Del</kbd>),
but it's never possible to close many windows.

Some behaviors I can see when having ~10 windows open and trying to close them all:

1. Window closes, but it creates a false duplicate entry for some other window
2. Window closes, but a wrong list entry is removed
3. Window closes, but the error `Window has vanished` appears in place of something else
4. Selected entry is removed, but nothing closes

I can always fully clear the window list, but the majority of the actual windows remain open. Closing and opening rofi again brings up a correctly updated window listing.

I'm using Openbox window manager.

Does the above list give any hint why keeping `window` open when removing entries might cause false entries appearing? Maybe I can test it out more robustly.

Rofi version number 1.7.0-1</div>

**Comment by DaveDavenport** [comment]
I was afraid of this might happen on some window manager when implementing this feature on request.
Given I did not get any feedback (And it worked on my i3 setup) I've kept it.

This feature probably has to be redone or removed.

**Comment by DaveDavenport** [comment]
The more I think about this, I think I might need to remove this feature. given it can take a while for windows to close, or popup dialogs when getting a signal to close, etc.

**Comment by DaveDavenport** [comment]
I'm going to remove this feature for now, the more I Think about it, the more broken it is.  I will leave this bug open an see if I can re-imagine this.

(I think i have a solution that would also make rofi more usable in f.e. `-normal-window` mode,
but it is a lot of work and no idea when I will have time to implement this.)

**Comment by DaveDavenport** [comment]
A bit more detail (if somebody wants to make a PR)

After deleting the window  and then reloading the window list will not work, given that events are not synchronized (the window can close after the list is reloaded).  If we want to fix this correctly, we need to listen for window create/destroy event from the Xorg server (need to lookup how to do that) and synchronize the view on this.   Once this is implemented then delete and staying open is a trivial implementation.

**Comment by DaveDavenport** [comment]
I've added another implementation that is hopefullly saner, can you test it?
Its not the most efficient yet (esp on creation of windows).
But the list should now stay in sync with the current state.

Branch i1404

**Comment by tuurep** [comment]
Hey Dave, thanks! I'm trying it out and seems like it works really well. So I can give info how it works on **Openbox**.

(Small nitpick, but to avoid any confusions: discussion num **1404** and number of this issue **1406** got mixed up in the branch name and commit msg. Or if Discussions are also a type of issue, then nevermind this.)

 I initially had difficulty building the rofi from that branch, but then saw section *Install a checkout from git* further down and figured that out.

Before building this, I removed arch distributed rofi (`pacman -R rofi`), I don't know if they would otherwise conflict. So this seems to work great, it uses my previous configs (`~/.config/rofi/ . . .`)

So I tried out the same kind of test case as in #1404:
* Opening about 10 windows and trying to close them all with `window` mode.
* Having different applications so it's clear if it removes a wrong listing.
* Goal: being able to clear the whole list and as a result, all open windows are closed.

Indeed everything worked! Was able to close everything correctly without closing `rofi` in between. No `Window has vanished` error messages anywhere. Tried multiple times, no problems found yet.

If you know of some edge cases that could be good to test, let me know.

Also I'm not sure how to uninstall this branch build and go back to the pacman version in the future. Could you give me a hint? Sorry for a newbie question, this is new to me.

**Comment by DaveDavenport** [comment]
```
make uninstall
```

**Comment by tuurep** [comment]
Testing in `-normal-window`:

Responds very well to updating the list according to launching/closing windows outside of rofi (tested with terminal, steam and browser).

One issue I can see with `-normal-window` + `close-on-delete: false;` is that sometimes pressing `delete-entry` (<kbd>Shift</kbd> + <kbd>del</kbd>) closes the rofi-window itself.

It doesn't happen every time, but usually within 5 consecutive deletes.

**EDIT:** Oh yes of course because I close the terminal window I launched rofi from.. So works good actually :D

**Comment by DaveDavenport** [comment]
Ill fix the 1404/1406 when squashing it and merging it.
I am gonna push a small update that 1.) reloads with a small delay (100ms) to avoid it reloading 10 times in a row.  2.) if you close rofi from rofi, rofi actually quits.
