### ISSUE TITLE
"Error" window get stretched if window border is relatively big

### ISSUE THREAD

**Issue by DaveDavenport** [davatorium/rofi#1437]
### Discussed in https://github.com/davatorium/rofi/discussions/1431

<div type='discussions-op-text'>

<sup>Originally posted by **Oxore** September  5, 2021</sup>
After number of experiments I narrowed down my `~/.config/rofi/config.rasi` to this:
```css
window {
    border: 5% 0;
}
```

I run `rofi` like this:
```sh
rofi -modi run -show run -no-default-config
```
I get what I expect on the "run" window (full screen shot):

![run](https://user-images.githubusercontent.com/17534278/132128529-75c0bd54-3b4b-41f0-8f73-c94c4c5583f5.png)

As you can see I type in `asdf` command, which does not exist in my system and then I get error message in, as I understand, a special "error" window:

![error](https://user-images.githubusercontent.com/17534278/132128572-21d27281-de2c-4472-835b-5cdcca67cce7.png)

There are two things appear unexpected to me:
1. The "error" window is stretched all the way down, I can't even tell where it ends.
2. Top edge of the "error" window is right at the center of the "run" window.

If I set window border to `4% 0` like this:
```css
window {
    border: 4% 0;
}
```

I get this result:

![error2](https://user-images.githubusercontent.com/17534278/132128760-dd30fe42-8ea7-4f88-b8eb-3cbcf925b583.png)

On this screenshot behavior 1 is gone, but behavior 2 is still present.

The same happens when I use `px` instead of `%` for border size. Pixel value must be around `50px` or above to reproduce the stretching problem in my case.

Is there a way to configure "error" window to make it **centered** and **not get stretched** when relatively large window border value is set?</div>

**Comment by DaveDavenport** [comment]
Can you try out:
```css
error-message { expand: false; }
```
to your theme. see if it works?

**Comment by DaveDavenport** [comment]
Pango indicates the text is 190 lines long, fun.
I think width is not set before height is checked, wonder why.

**Comment by DaveDavenport** [comment]
There is a nice race condition going on there. 
I re-did part of the sizing logic that should now be more correct in git!
Please check if it works. (This needs testing!!)

**Comment by DaveDavenport** [comment]
hmm I found a bug myself already. fun

**Comment by DaveDavenport** [comment]
put it on a branch i1437.

**Comment by Oxore** [comment]
> Can you try out:
> `error-message { expand: false; }`
> to your theme. see if it works?

Yes, on my setup the error window does not become stretched, when `error-message { expand: false; }` is set. Tested on commit 294a22f3.

I checked out the `i1437` branch (commit f785dad2) and after rebuild I see that error window does not get stretched anymore even without configuration proposed above. That's cool! Looks like one problem is solved.

Frankly, this does not fix my little, humble use case, which I did not say anything about explicitly. I want to use `border: 50% 30%` for `window` to make sure my screen is always filled with mono color around the list view when Rofi runs. But error window is being rendered with the top edge right at the center of the screen and 50% border drags window body all the way down beyond the screen surface. So I can't see the error message at all, heh. I would like to see it, honestly. Is it a bug too or can it be solved by proper configuration?

Anyway, thank you for your work!

**Comment by DaveDavenport** [comment]
a border of 50% is invalid, as it leaves no room for anything.
you have 50% on the left, 50% on the right (or top/bottom) and no space is left
Maybe something like
```css
window { fullscreen: true; }
```
and play with margins/padding will work better?

**Comment by DaveDavenport** [comment]
Ill see if I can make a demo theme tomorrow. (and see if we have another bug here). I don't think the error window is well tested.

**Comment by DaveDavenport** [comment]
On the i1437 branch this seems to work for me:
```bash
rofi -show combi -theme-str 'window {fullscreen: true; padding: 10%; } error-message { padding: 20% 20% ; background-color: lightgreen; } textbox { vertical-align: 0.5; horizontal-align: 0.5; background-color: red/20%; } ' -e "test" -no-config
```

**Comment by Oxore** [comment]
Thank you! Setting just `window { fullscreen: true; padding: 42% 30%; }` does the work and is sufficient for my theme with my current screen on `i1437` branch. Gonna test it with 4K on wayland today.

I've been using `window { border: 50% 30%; }` because in combination with `listview { lines: 3; }` it give consistent listview height across displays with different resolutions. Setting `window { fullscreen: true; }` with padding gives inconstistent listview height. But actually today I use displays with height of 1080px mostly and proposed solution probably solves my problem.

**Comment by DaveDavenport** [comment]
As I said,  a border of 50% is invalid as there is no space left.

Wayland is not officially supported by rofi.   (see https://github.com/davatorium/rofi/wiki/Wayland)

**Comment by Oxore** [comment]
Fortunately it is consistent on wayland with 4K screen, because wayland scales all X11 apps to look like on Full HD screen. I will stick to proposed configuration instead of 50% border value.

> Wayland is not officially supported by rofi.

Thank you for the clarification.

Wayland is irrelevant here. I mean if I have two screens with different heights in pixels (let's say 1366x768 and 1920x1080), then proposed solution with window's fullscreen and padding parameters will result in different number of lines in listview, which I was trying to mitigate initially. But for me is not really meaningful anymore. I am fine with it. since now on all screens I currently use rofi behaves more or less the same way. My problem is fully resolved. I will resolve related discussion soon.

But I will be here to help with testing if needed at least untill the issue is closed.

**Comment by DaveDavenport** [comment]
I just made the wayland disclaimer as we had very weird behaviour with X on wayland before (and I want to avoid people complaining later that I did accept wayland here, but not in their case).  

Good to hear that the branch fixes it, I will merge it into main soon.
