### ISSUE TITLE
[REQUEST] ELF.tgz download from releases page

### ISSUE THREAD

**Issue by Tcll** [davatorium/rofi#1624]
### Before opening a feature request

- [X] I checked the *next* branch to see if the feature has already been implemented
- [X] I searched existing reports to see if it is already requested.

### What is the user problem or growth opportunity you want to see solved?

on the [release](https://github.com/davatorium/rofi/releases) page, I'd like to be able to download a pre-built portable binary packed in a tar.gz

if I had to give an example, look at the downloads page on blender.org
or for a more closely related example [schismtracker](https://github.com/schismtracker/schismtracker/releases)

or at the very least, you could grab an AppRun from [AppImageKit](https://github.com/AppImage/AppImageKit/releases/latest) and pack a `rofi.AppDir/` to use appimagetool on and build a user-friendly AppImage to download like [conky](https://github.com/brndnmtthws/conky/releases) provides.
(I've already built my own rofi 1.5.4 (Ubuntu 21.04 from pkgs.org) AppImage, but wouldn't claim it suitable for public use, plus its not official to be trustworthy)

### How do you know that this problem exists today? Why is this important?

because the tar.gz provided does not contain a portable binary

### Who will benefit from it?

normal users
or advanced users who don't want to be forced to compile everything they want to use (like me)

### Rofi version (rofi -v)

1.5.4

### Configuration

not needed

**Comment by DaveDavenport** [comment]
As mentioned on other related requests,  I have 0 time nor intention to maintain a binary release/appimage/snap or maintain distribution packages and nobody else has offered to take on this task.

**Comment by DaveDavenport** [comment]
See  #1329 and bullet point 2 of [this](https://github.com/davatorium/rofi/blob/next/.github/CONTRIBUTING.md#creating-a-bug-report).

**Comment by Tcll** [comment]
> and nobody else has offered to take on this task.

you are the developer, it's your job to provide users with a suitable binary for your software if you want them to use it...
you can't expect others to do your job for you.

just like it's my job to provide users with a binary of my software (when finished):
https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/d9bc6087337ed28ef1da653d6561bf57849f09c89e08116466b4a283aee0a199
(GitHub malware won't allow me to upload images)
and no I'm not using fake GitLab either, you'll find my provided GiTea repo of Libre FOSSware at my I2P address when I can actually take the time to set it up.

and providing a binary doesn't make it any less open source
add to that why would I sully my reputation by providing malware in the software I'm providing you?
only an idiot would do such nonsense.

**Comment by dannycolin** [comment]
> you are the developer, it's your job to provide users with a suitable binary for your software if you want them to use it...

Rofi isn't a commercial product. It's shared **as is**. Dave and others aren't freaking paid for it. If they don't want to do the extra work they're 1000% justified not to do so.

Also, in the Linux ecosystem, it's often the distributions that package applications and Rofi is available on a lot of them already. If yours isn't in the list then I invite you to contribute in a meaningful way to the community by voluntaring time to package it. Another solution would be to create a PR for a patch that could use GitHub Action to create a binary when a new release is pushed.

Since, you seems to also be a developer, I'm sure you should be qualified enough to contribute to this.

Have a nice day.

**Comment by DaveDavenport** [comment]
I have no idea where the malware story comes from, or the fake gitlab (I know gitea, ran it for a while).
I don´t understand this complete rant ?  nobody accused you or anybody of anything, you bought it up,
You seem to respond to a personal attack that has never been made.

The only reason why i remarked that nobody offered to take on this task, because it is the truth, as far as I know nobody is maintaining a binary release (except distro packages). 

I will lock this thread as I have no time or energy to deal with this.
