### ISSUE TITLE
[BUG] Rofi is noticeably slower in 1.7.4 compared to 1.7.3

### ISSUE THREAD

**Issue by isak102** [davatorium/rofi#1683]
### Rofi version (rofi -v)

Version 1.7.4

### Configuration

https://gist.github.com/isak102/a2de88e1926aa02de06cf0bc72eb8cfd

### Launch command

rofi -dmenu 

### Step to reproduce

1. Install rofi 1.7.3 and note the response time between typing the characters and the search list updating
2. Do the same with rofi 1.7.4
3. Note the difference

### Expected behavior

The matches of what you type should show up almost instantly, like it does in 1.7.4. For example, typing "abc" should show all matches with abc almost instantly. 

### Actual behavior

Instead of showing the matches instantly, it is very slow in 1.7.4. It takes a noticeably longer time to update the search results compared to 1.7.3. 

### Additional information

My distro is Arch Linux

**Comment by DaveDavenport** [comment]
please try the latest release several changes to dmenu went in.

Also provide a timing log and method to reproduce.
(for me speed is equal between 1.7.3 and 1.7.4, but context matter!)

**Comment by DaveDavenport** [comment]
If this happens on large lists, try increasing `-refilter-timeout-limit`.
After 8192 lines, rofi will wait filtering until you done typing.

**Comment by DaveDavenport** [comment]
Changed the limit to be in time .
So on first filter it tracks the time it takes, and based on that switches over to delayed filtering.. Default 300ms.

**Comment by isak102** [comment]
> please try the latest release several changes to dmenu went in.
> 
> Also provide a timing log and method to reproduce. (for me speed is equal between 1.7.3 and 1.7.4, but context matter!)

It's the same in 1.7.5, its very slow compared to 1.7.3. Its mostly on large lists but it feels slower even on smaller lists aswell. How do I provide a timing log? Is there a flag to do that?

edit: I can make a screen recording and demonstrate the difference tomorrow

**Comment by DaveDavenport** [comment]
For getting timing log, see the text provided when you made this issue: It explicitly asked for this and links to how!
A screencast is not very useful.

also give actual numbers. 'large list'  'smaller lists'  does not say anything.  it could be 100 and 3 or 10000000 and 100000.

Please try latest git, as I tweaked the algorithm a bit.

Rofi should not be slower (filtering has not changed), what happens is after a certain amount of rows (8192 in 1.7.5, this limit might be low) it waits until you stop typing to filter. You can test this in 1.7.4-1.7.5  with the option I mentioned before.
This was added because on large lists filtering after each character input causes a lot of (unneeded) work and slows things down a lot.
I agree, it might switch (depending on speed pc) to soon to this mode. I've tuned this to very low end hardware.

Therefor I've changed it in git to switch to this mode if the filtering action takes more then 0.3 Seconds. 
Please test this.


Without people testing before a release, its hard to get these things right.

**Comment by isak102** [comment]
I tried the latest git commit and the speed is now the same as 1.7.3, so it is working as expected. Thanks :)

**Comment by DaveDavenport** [comment]
Speed never changed, only changed how/when it responded. But happy to hear it is fixed, I think this is a better solution (also has it downsides).
