### ISSUE TITLE
[BUG] Rofi doesnt show window actual workspace 

### ISSUE THREAD

**Issue by ParthenGithub** [davatorium/rofi#1699]
### Rofi version (rofi -v)

Version 1.7.5

### Configuration

https://gist.github.com/ParthenGithub/963c0c4029aa50cea1f4099d7832ad13

### Theme

https://gist.github.com/ParthenGithub/074ee202c310f3aaec22a5b575841414

### Launch command

rofi -show window -theme /home/parthen/.config/rofi/launchers/type-2/style-2.rasi

### Step to reproduce

* I install type 2 style 2 theme from here https://github.com/adi1090x/rofi
* Then run command  ```rofi -window``` with this theme 

### Expected behavior

Expecting rofi to show windows with their actual workspaces

### Actual behavior

Rofi show windows with workspaces on moment of i3wm update. If i move windows on other workspaces, rofi still show that they're not moving. 
If i press hotkeys to update i3wm, rofi also updates

### Additional information

I use Artix Linux, xfce4, i3wm.

**Comment by DaveDavenport** [comment]
I don't really understand what the problem is, its a bit confusing:

* What is `i3wm update`? 
*  `rofi -window` is not a valid rofi command.

When launching rofi,  rofi queries the Xorg server for the current list of windows/workspaces at that point in time..  This information is set by the window manager.  If it shows wrong/outdate information, then the information set by the window manager is wrong. 
*rofi is stateless between launches*, so if information is outdated between runs its unlikely rofi fault.

Given you have to 'i3wm update' (I have used i3 for many years, never heard of having to manually update i3...)  to get it right, i think information is not correctly updated by the wm. you can check this yourself with `xprop -root`.

(Rofi normally grabs all keys and runs on top of everything,  so you should not be able to change windows layouts while it is running.
For me in `-normal-window` mode where it runs as a normal window, the workspace instantly updates when I move windows around.
)

**Comment by ParthenGithub** [comment]
Sorry, just my bad English.
On ```i3wm update``` I mean restart of window manager, which is doing by pressing $mod+Shift+R
And of course valid command is ```rofi -show window```

What I can also add -- apps after their moving show on #10 workspace, which is my default workspace for second monitor.

And what is more confusing -- Rofi does take me to the selected window, as if it knows which workspace it is actually in

**Comment by DaveDavenport** [comment]
Given my previous remark about rofi being stateless,  if between runs it shows old information, something is wrong with your setup. Having  to restart i3 to fix this, seems to confirm this.
I don't think this is a rofi bug, as it queries the information fresh from X on each run.

**Comment by DaveDavenport** [comment]
might be interesting to use a tool like 'wmctrl -l' to figure out what is going on.
