### ISSUE TITLE
Feature request: Default entry matching option

### ISSUE THREAD

**Issue by samhh** [davatorium/rofi#742]
## Version

1.4.2

## Steps to reproduce

* Launch Rofi with any modi and any matching method.

## What behaviour you see

* Before you type anything there will already be a match. Presumably this is based upon either your history or alphabetical order.

## What behaviour you expect to see

* At least an option to prevent anything from showing up if your search term is empty.

**Comment by DaveDavenport** [comment]
The textbox in rofi is a *filter* not a *search*. The current behavior is correct and intended.

**Comment by SamHH** [comment]
I understand that the behaviour is technically correct. I feel there are some upsides to adding this sort of functionality, though, albeit optionally. Speaking for myself:

- I find it quicker to type what I want to open rather than spend a second grepping what I see is preselected (given that it may change over time and take me by surprise if I hit enter too presumptuously), so I see no benefit in having something preselected.

- I use passmenu (for pass) and have it configured to work via Rofi rather than dmenu. There's no history here, it's just alphabetical by default. This means I always see the same pass entry by default, despite the fact there's a ~1/500 chance of that being what I'm actually looking for. So, again, the preselection doesn't benefit me, and this probably applies to other use cases as well.

- Very subjectively, with the above in mind, I think it's just kind of ugly. You wouldn't show anything when the filter fails to match anything (because that would be useless), why show something when the filter term is empty (equally useless)?

Ideally I'd love there to be something like a `--no-empty-match` option that simply gives you nothing back as a result if your search term is empty.

Alternatively I wonder if there's some way to do this via a Rasi theme. How similar is Rasi to CSS? Because in CSS I might try something like this:

```css
input[value=""] + .results {
  visibility: hidden;
}
```

**Comment by sardemff7** [comment]
The list has selectable items, the input is **only used to filter it**. On top of this filter, there is a sorting algorithm to list items in the what-you-most-likely-mean order. So typing nothing is **not** useless, I do that very often.

**Comment by sardemff7** [comment]
The list has selectable items, the input is **only used to filter it**. You can see that when you select a different item, the input field does not change. On top of this filter, there is a sorting algorithm to list items in the what-you-most-likely-mean order. So typing nothing is **not** useless, I do that very often.
I have in my `run` history an `xrandr --auto` and an `xrandr --output VGA-1 --off`, that allow me to quickly (de)activate my second screen on my laptop, whether or not I’m using it for my desktop. I never ever type anything, I only hit `Enter` or `Down` then `Enter` to run the wanted command.
A lot of tools also use rofi to be a menu, like [teiler](https://github.com/carnager/teiler).
You can make something similar to what you want by tricking rofi in a C plugin, I think, but you are on your own there.

The rasi format is similar to CSS when it comes to the syntax, but selectors are quite fixed and do not follow the fancy CSS3/4 stuff.

**Comment by SamHH** [comment]
Well that's my point, it's potentially useless based upon use case, hence my desire for an option. I'm certainly not prescribing changing the default functionality.

**Comment by sardemff7** [comment]
And my point is (independently of whether or not it should be implemented or not): why does it matter at all? “Useless” as in “not wanted” does not mean “wanted not to”. You are in no way forced to read these lines, you can even show only one and it’ll look quite neat anyway.

**Comment by SamHH** [comment]
As it happens I do display one line, always, but it's quite visually unpleasant to see that one line when none of my multiple personal use cases benefit from it. If there were no results for an empty filter I may prefer to show multiple, but I feel I can't.

I guess this disagreement boils down to whether we feel a subjective opinion on "visually unpleasant" matters or not. It does to me given that I doubt I'm the only one who'd prefer this, particularly coming from macOS and Spotlight / Alfred.

Unrelated: That commit looks interesting... :-D

**Comment by DaveDavenport** [comment]
There is now (in upcoming release) an option to hide the listview when no text is entered.
