### ISSUE TITLE
Rofi shouldn't accept entry not in the list in drun mode

### ISSUE THREAD

**Issue by dannycolin** [davatorium/rofi#966]
## Version

1.5.2-88-g361ce7d6-dirty (next)

## Configuration

https://gist.github.com/dannycolin/06c428445282248b3040bd862958550d

## Launch Command

rofi -show drun

## Steps to reproduce

* Open Rofi
* Enter a program name not in the list

## What behaviour you see

* Rofi main window closes and open an error window 

## What behaviour you expect to see

* Rofi should do nothing if the list is empty.

### Why

This behavior will avoid the need to close the error message window and reopen Rofi main window if Rofi return a _Failed to execute: <program name>_ error.

## Notes

IRC log :
```
sdk | Q: If I make a typo in drun mode, Rofi closes its main window and shows a error window. I wonder if it would be possible to show that error in the main window so I wouldn't need to close (esc) the error window and reopen rofi.
@SardemFF7 | sdk: sounds doable, not sure how this was designed but maybe just adding a widget instead of a window would work… 
qball | that could easily be changed.
```

**Comment by DaveDavenport** [comment]
The window needs to disappear  (and release focus) so the new application can grab focus.
(for example launching rofi from rofi would otherwise break).

But it can be changed to pop backup at the point it was.

**Comment by dannycolin** [comment]
> The window needs to disappear (and release focus) so the new application can grab focus.

In that case (drun mode only), Rofi try to launch a .desktop that doesn't exist. Would it be possible to check first if the target exists before launching it? If yes, Rofi closes and if not, Rofi show the display the error widget.

**Comment by DaveDavenport** [comment]
>  Rofi try to launch a .desktop that doesn't exist.

The desktop file exists, the exec might not be possible, we might not be able to find out it will fail beside just trying it :D

**Comment by sardemff7** [comment]
We could do some check if `TryExec` is present. Not sure when though. The “best” would be when building the list, but it’ll slow it down quite a bit, unless we build a cache.

We could also release our grab and keep the window around until some timeout and if the program is still running, assume it didn’t fail (currently, we close rofi so I guess we already have some timeout around).

**Comment by dannycolin** [comment]
> The desktop file exists, the exec might not be possible, we might not be able to find out it will fail beside just trying it

Ah true. That case is also possible. I think as long as Rofi reopen if it hits a "failed to exec" that would be enough. Something like :

1. Open rofi
2. Type a typo and press enter
3. Rofi closes to release focus
4. Rofi encounter a "fail to exec error" and reopen itself with an error widget instead of just an error window.

**Comment by DaveDavenport** [comment]
Around 10% of the desktop files in my /usr/share/applications/ has `TryExec` set.

**Comment by dannycolin** [comment]
> Around 10% of the desktop files in my /usr/share/applications/ has TryExec set.

@DaveDavenport I don't think we need `TryExec` to check if the executable exists. Don't we?

**Comment by sardemff7** [comment]
We do, because it’s the only reliable way to do so by the spec. Trying anything else will lead to a failure for someone and will be a genuine bug.
`TryExec` is mainly meant for `.desktop` file that you always install at the distribution level even if the required software is not actually installed.
This is *one* check we **can** do by the spec, so we probably should do it, somewhere.

However, your issue will not be magically fixed by that, I agree.

What I suggest is that we keep rofi’s window around a bit longer, releasing the grab, and see if the exec failed or not. It *should* be seamless when it works, and almost seamless when it fails, grabbing back “quickly enough”.

Nevertheless, I am still not clear on your exact issue.
If this is about an history entry for a `.desktop` file that doesn’t exist any more, it should be covered by such a fix (and just as well for the `run` mode, btw).
If this is about a real `.desktop` file that fails, I’d argue it’s a non-rofi issue that should be fixed elsewhere. And I’d like to know what other launchers do in that case, if they do anything at all.

**Comment by dannycolin** [comment]
> We do, because it’s the only reliable way to do so by the spec

Ah I see. Very sad that no one is following the spec tho.

> Nevertheless, I am still not clear on your exact issue.
> If this is about an history entry [...].
> If this is about a real .desktop file that fails [...].

@sardemff7 It isn't about history nor a .desktop file. It's about Rofi launching in **drun mode** a program that doesn't exist.

For example, let's say I want to open Vim. I open Rofi, type Cim (or any other form of typo) and press enter. Keep in mind that I'm used to press my binds so I'm not even looking at the list nor the list have the time to filter sometimes. Anyways, Rofi will try to launch "Cim" and since it doesn't exist Rofi will return an error window with a message saying so. Because of that, I'll need to close that error window and reopen Rofi. IOW, it isn't an agreeable UX.

So what I'm asking is would it be possible to instead of opening an error window that Rofi reopen itself with the error message inside an error widget. I mean, there's no need to wait to anytime or releasing the grab. If Rofi can open an error message window then it can definitely reopen itself at that point.

**Comment by sardemff7** [comment]
Ok so that’s an entirely different issue. It basically boils down to “`drun` must not accept entry not in the list”. `drun` doesn’t launch programs, it launches `.desktop` files, so it is a `.desktop` file issue, kind of.

And here, `TryExec` wouldn’t help of course, because there is no file to read it from. :-)
(Btw, it’s not “not following the spec” to omit it. If you install a `.desktop` file you **do** expect the executable to be installed to, so the check would just be wasted time, except in a few cases where you can use `TryExec`.)

Sure the error message is a bit of a misfeature here, but it’s not the essence of the bug.
Your original report just mentioned a typo, but it’s much more specific. A typo might match any other random `.desktop` file that would *then* fail to launch for an entirely different reason.

**Comment by dannycolin** [comment]
> Ok so that’s an entirely different issue. It basically boils down to “drun must not accept entry not in the list”. drun doesn’t launch programs, it launches .desktop files, so it is a .desktop file issue, kind of.

@sardemff7  I've updated the issue to reflect what you said in your latest comment.

**Comment by dannycolin** [comment]
Thanks :)
