### ISSUE TITLE
Error "symbol(s) not found for architecture x86_64" when trying to install rofi (make)

### ISSUE THREAD

**Issue by VonbatenBach** [davatorium/rofi#989]
## Version

Not installed yet.

## Configuration

Not installed yet.

## Launch Command

Trying to install rofi, following an installation guide for "Install from a release" option.

## Steps to reproduce

* ../configure command does not give an error

* make command gives the following message:

## What behaviour you see

* `../script/get_git_rev.sh .. ./gitconfig.h `
`/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am`
`../script/get_git_rev.sh .. ./gitconfig.h`
 ` CCLD     rofi`
`Undefined symbols for architecture x86_64:`
  `"_strchrnul", referenced from:`
`      _combi_mode_result in rofi-combi.o`
 `     _combi_preprocess_input in rofi-combi.o`
`ld: symbol(s) not found for architecture x86_64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make[1]: *** [rofi] Error 1`
`make: *** [all] Error 2`

## What behaviour you expect to see

* I'd expect to make without any error :)

**Comment by sardemff7** [comment]
Version is still important. If you use a release, we need the version (and the link to the tarball to be sure we have the same). If you use git, run `git describe --tags`.

We also need the exact command you use, and what system you have. Do you use glibc or another libC?
Then we need your `config.log`, you can upload it on this issue directly (drap&drop in the comment box).

As a workaround, could you try to build rofi with Meson?

**Comment by VonbatenBach** [comment]
`git describe --tags` returns `1.5.4-3-gbe21fbae`.

I use OSX.

Exact commands I use are:
`git clone --recursive https://github.com/DaveDavenport/rofi
cd rofi/`
`autoreconf -I`
`mkdir build && cd build`
`../configure`
`make`

[config.log](https://github.com/davatorium/rofi/files/3362399/config.log)

I tried to build rofi with Meson but it didn't work.
I don't know what are glibc or libC...

**Comment by sardemff7** [comment]
Why `autoreconf -I` and not `autoreconf -i` as `INSTALL.md` says?
Also, this is a Git build, and you told us you used “Install from a release” instruction. Not that important, but did you actually use the “Install from Git” section or just guessed the commands?

Then the elephant in the room: rofi was never(?) tested on OSX, I don’t have such a system to test it.
So you **are** using non-glibc, and it’s most likely the issue here.

I think Meson would have more chances to not explode on us there, though Autotools should work too, in theory. Either way, we’ll have to tweak the build or the code for that.

I didn’t spot anything suspicious in `config.log` but I’m not exactly an MacOS expert.
I will need the output of `make V=1` to see which command fails exactly.
And if you could share the output of `meson setup build` (and `ninja -C build -v` if `meson setup build` passes) that may help. (At least I’d want to fix both build systems if anything is needed there.)

**Comment by VonbatenBach** [comment]
Of course, I used `autoreconf -i`, just a missclick ;) 
I followed instructions. At the end of the "git section" is written: From this point, use the same steps you use for a release.

Output of `make V=1`:
[outputV1.txt](https://github.com/davatorium/rofi/files/3362537/outputV1.txt)

Output of `meson setup build`:
[setbuild.txt](https://github.com/davatorium/rofi/files/3362547/setbuild.txt)

Output of `ninja -C build -v`:
[ninja.txt](https://github.com/davatorium/rofi/files/3362550/ninja.txt)

**Comment by DaveDavenport** [comment]
I have added a check to configure to check for strchrnul. Hopefully next time there is a decent error message before compilation.


I hate having to do this, but I don't think I want to support MacOS.

* Rofi is heavily dependent on X11. There is no native backend for it.  So it will never integrate well.
* I see little use for it (dmenu? possibly) and I think the number of users will be low.
* I have no (recent) machine with this operating system.  The systems are to expensive for me to obtain one for rofi development.
* I have little time to work on rofi as is.

Patches/help is always welcome.
